name: CI/CD for Server

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_1 }}

on:
  push:
    branches:
      - main

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./server
        run: npm install

      - name: Run Tests
        working-directory: ./server
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test

      - name: Deploy to Server
        working-directory: ./server
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
